### ISSUE TITLE
how can i make a marginal lua script?

### ISSUE THREAD

**Issue by EvertVanRompaey** [poky1084/Limbo#1]
This wont work

nextbet = 0.123083 --sets your first bet.
target  = 2 -- set target

function dobet()
    if (win) then
        print("result: " .. lastBet.result)
        nextbet = 0.123083
    else nextbet *2 
    end
end

**Comment by reboot337** [comment]
hey bro

```
function dobet()
  if win then
      nextbet = base
  else
      nextbet = previousbet * multiplier
  end
end
