### ISSUE TITLE
fix roulete to pls

### ISSUE THREAD

**Issue by xazes** [poky1084/Limbo#5]
I see your c# Limbo in c# works? Can you fix roulette?

**Comment by xazes** [comment]
p.s. i run your roulelte programm with your nodejs proxy and it works fine

**Comment by poky1084** [comment]
yeah with the localhost proxy all bot should work with replaced urls

**Comment by poky1084** [comment]
https://github.com/poky1084/StakeLoader here is the update with the pupflare cloudflare proxy. 
there is a video with installation https://www.youtube.com/watch?v=0ppG4Q31QEs
